name: github pages

on:
  push:
    branches:
      - master
      - mdbook

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.1'
          # mdbook-version: 'latest'

      # This generates the book inside ./book/book
      - run: mdbook build book

      # Build the cargo doc and copy it to ./book/book/doc
      - name: Build the doc
          run: |
            cargo doc --no-deps
            cp -r target/doc book/book/doc
            echo "<meta http-equiv=refresh content=0;url=pravega_client_rust/index.html>" > book/book/doc/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book/